### ISSUE TITLE
Pothos GUI multi document interface

### ISSUE THREAD

**Issue by dimitarpenev** [pothosware/pothos#113]
I think it may have advantages to be able to 'undock' the different tabs from the Pothos GUI in a separate windows. 
For a big diagrams we would be able to arrange those windows better, especially having few monitors available.
I am not sure if this can be achieved easily using the current status of the software.

**Comment by guruofquality** [comment]
Thats a pretty good idea and its inline with some other gui improvements I was thinking about: https://github.com/pothosware/pothos-gui/issues/102

**Comment by guruofquality** [comment]
This issue was moved to pothosware/pothos-gui#147
