### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by sirinath** [pothosware/pothos#31]
As guidance perhaps you can benchmark against similarly frameworks. Though not exact matchers include: http://www.seastar-project.org/, http://actor-framework.org/, http://www.ponylang.org/

**Comment by guruofquality** [comment]
The plan was to launch a benchmark suite after the JSON stats API was implemented. That way it becomes very easy with script a topology with python, run it, gather the results, make nice plots with matplotlib (or similar). Anyway, the JSON stats are in now and FWIW, I did use them to do some basic profiling on the scheduling overhead.

Anyway, the issue for the benchmarks is here: https://github.com/pothosware/pothos/issues/5 And I would be interested to learn about any particular topologies that are of interest, worth optimizing for, or useful for comparison purposes.
