### ISSUE TITLE
cmake accepts versions of poco which are too old

### ISSUE THREAD

**Issue by xloem** [pothosware/pothos#37]
I have poco 1.4.6 installed.  cmake is selecting my system poco, but I do not have the JSON component, and build fails.

**Comment by guruofquality** [comment]
Good point. Theres some other incompatibilities with the much older Poco. So version check is probably best. My intuition here is to parse Version.h for POCO_VERSION with cmake regexps when poco is found. We can do this in https://github.com/pothosware/pothos/blob/master/library/cmake/SetupPoco.cmake And then add a version check to the top level CMakeLists.
