### ISSUE TITLE
Dropping MSVC 2012 support: variadic templates and more

### ISSUE THREAD

**Issue by guruofquality** [pothosware/pothos#91]
**We ended up not using variadic templates** to support MSVC2012 which had incomplete c++11 support. Now that 2012 is dropped in favor of the more compliant 2013 and 2015, we should cleanup use of generated headers using variadic templates.

* [x] All of the Callable, Proxy, ManagedClass APIs can be cleaned up. There is no need for this template generation system: https://github.com/pothosware/pothos/blob/master/include/CMakeLists.txt#L38

**Further, we avoided certain API calls** because it would require even more generation like this, so...

* [x] Create a templated emit() API call on Pothos::Block to replace the use of callVoid(signalName, args...)
* [x] Create a BlockRegistry::make(path, args...) factory call to neaten all of the BlockRegistry invocations that operate in the current process.
* [x] Create emplace back/front for RingDequeue. Example InputPort uses a pair for holding async messages and slots, which can be emplaced back instead.

**Other misc VS2012 work arounds**:

* [x] remove pothos_explicit ifdef in Config.hpp (use explicit)
* [x] remove MathCompat.hpp, all of these functions were for 2012
* [x] revert unit tests used list initialization for test vectors but were "fixed" for 2012

**Finally**:

* [x] update blocks packages to use emitSignal() and unit tests to use BlockRegistry. Do this after the merge. Also remove includes of mathcompat.hpp

**Comment by guruofquality** [comment]
Done! This does mean that many of the submodules master branches only compile with the master branch of pothos. But thats bounds to happen with API additions.

**Comment by gvanem** [comment]
These `comms` files:
```
waveform/NoiseSource.cpp
waveform/WaveformSource.cpp
digital/SymbolMapper.cpp
```
still seems to have this:
```
#include <Pothos/Util/MathCompat.hpp>
```

Aren't those DLLs supposed to be built? But for me, things compile on MSVC-2015 w/o this header.
